### ISSUE TITLE
OpenSSL::SSL::SSLContext expected

### ISSUE THREAD

**Issue by aplatypus** [jamesgolick/always_verify_ssl_certificates#3]
Hi James

I've had a problem with SSL using gtranslate-two (on github) with jRuby
-  https://github.com/marcinwyszynski/gtranslate-two

Anyway I get the same issue with Ruby 1.9 too and while I expect the problem is some place between gtranslate-two and the HTTP.rb module, there's little in the way of diagnostics to point me in the right direction.

Is there a 'verbose' mode or something that I can use?  There's a small IRB session below.

Thanks,

  Will

-----------[  irb session  ]------------------

```
irb(main):001:0>  require 'gtranslate-two'
=> true
irb(main):002:0> require 'always_verify_ssl_certificates'
=> true
irb(main):003:0> GTranslator.key ="(key)"
 => "(key)"
irb(main):004:0> new_text = GTranslator.translate( "hello world.", GLanguage::Chinese_Simplified, GLanguage::English )
 TypeError: wrong argument (NilClass)! (Expected kind of OpenSSL::SSL::SSLContext)
    from c:/bin/ruby/v1.9/lib/ruby/gems/1.9.1/gems/always_verify_ssl_certificates-0.2.0/lib/always_verify_ssl_certificates.rb:13:in `initialize'
    from c:/bin/ruby/v1.9/lib/ruby/gems/1.9.1/gems/always_verify_ssl_certificates-0.2.0/lib/always_verify_ssl_certificates.rb:13:in `new'
    from c:/bin/ruby/v1.9/lib/ruby/gems/1.9.1/gems/always_verify_ssl_certificates-0.2.0/lib/always_verify_ssl_certificates.rb:13:in `connect'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/net/http.rb:637:in `do_start'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/net/http.rb:626:in `start'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:769:in `buffer_open'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:671:in `open'
    from c:/bin/ruby/v1.9/lib/ruby/1.9.1/open-uri.rb:33:in `open'
    from c:/bin/ruby/v1.9/lib/ruby/gems/1.9.1/gems/gtranslate-two-0.1.3/lib/gtranslate-two.rb:21:in `translate'
    from (irb):4
    from c:/bin/ruby/v1.9/bin/irb:12:in `<main>'
```

**Comment by leahy16** [comment]
Hi James,
I'm getting the same error with Rails (3.0.5) & Ruby (1.9.2p180). This is occurring across two gems, activemerchant (1.12.0) and oauth2 (0.1.1). Can you offer any solutions?

Patrick

**Comment by loe** [comment]
1.9 compat. 1.9 uses VERIFY_PEER by default, so unless you know you have a library turning it off, you're probably ok.
