### ISSUE TITLE
Wrong argument (NilClass)

### ISSUE THREAD

**Issue by cmer** [jamesgolick/always_verify_ssl_certificates#5]
/Users/carl/.rvm/gems/ruby-1.9.2-p136/gems/always_verify_ssl_certificates-0.3.0/lib/always_verify_ssl_certificates.rb:17:in `initialize': wrong argument (NilClass)! (Expected kind of OpenSSL::SSL::SSLContext) (TypeError)
    from /Users/carl/.rvm/gems/ruby-1.9.2-p136/gems/always_verify_ssl_certificates-0.3.0/lib/always_verify_ssl_certificates.rb:17:in`new'
    from /Users/carl/.rvm/gems/ruby-1.9.2-p136/gems/always_verify_ssl_certificates-0.3.0/lib/always_verify_ssl_certificates.rb:17:in `connect'
    from /Users/carl/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/net/http.rb:637:in`do_start'
    from /Users/carl/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/net/http.rb:626:in `start'
    from /Users/carl/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/net/http.rb:1160:in`request'
    from /Users/carl/.rvm/gems/ruby-1.9.2-p136/gems/httparty-0.7.4/lib/httparty/request.rb:69:in `perform'
    from /Users/carl/.rvm/gems/ruby-1.9.2-p136/gems/httparty-0.7.4/lib/httparty.rb:394:in`perform_request'
    from /Users/carl/.rvm/gems/ruby-1.9.2-p136/gems/httparty-0.7.4/lib/httparty.rb:346:in `get'
    from /Volumes/1TB Storage/Carl/Dropbox/code/opensource/contextio/lib/contextio/request.rb:79:in`get'
    from /Volumes/1TB Storage/Carl/Dropbox/code/opensource/contextio/lib/contextio/request.rb:22:in `all_files'
    from test/unit/test.rb:9:in`<main>'

**Comment by loe** [comment]
1.9 compat. This isn't really necessary as VERIFY_PEER is the default. It is possible that another library disables this for you.
